Repository margual56/radio-cli, pull requests merged in 2022-05, with the labels that each got.

#9 Replace the Cli struct powered Structopt by a new one backed by Clap v3
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: enhancement, good first issue

#11 ci(refactor_jobs): split the job into several jobs
  .github/workflows/rust.yml
  src/main.rs
Labels: enhancement

#15 Update README's references to the mpv dependency
  README.md
Labels: documentation
